[mgr]
cwd = { fg = "#50fa7b" }

[filetype]
rules = [
	# Fallback
	{ url = "*", fg = "#f8f8f2" },
	{ url = "*/", fg = "#bd93f9" },
]

[icon]
dirs = [
]
conds = [
	# Fallback
	{ if = "dir", text = "", fg = "#bd93f9" },
]
