source ~/.dotfiles/zsh/.config/zsh/env.zsh
source ~/.dotfiles/zsh/.config/zsh/zim.zsh
source ~/.dotfiles/zsh/.config/zsh/aliases.zsh
source ~/.dotfiles/zsh/.config/zsh/vi.zsh
source ~/.dotfiles/zsh/.config/zsh/mappings.zsh
source ~/.dotfiles/zsh/.config/zsh/themes.zsh
source ~/.dotfiles/zsh/.config/zsh/television.zsh
source ~/.dotfiles/zsh/.config/zsh/completion.zsh
source ~/.dotfiles/zsh/.config/zsh/fonts.zsh
source ~/.dotfiles/zsh/.config/zsh/plugins.zsh
