# 指定shell为zsh，在tmux中也指定了
shell zsh

# 自动启动tmux新建或连接会话main
# shell tmux new-session -A -s main

# 隐藏窗口装饰（关闭标题栏）
hide_window_decorations yes 

# 字体设置
font_family	ComicShannsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 15

# 设置备用字体
symbol_map U+4E00-U+9FFF LXGW WenKai GB Screen
symbol_map U+3400-U+4DBF LXGW WenKai GB Screen
symbol_map U+20000-U+2A6DF LXGW WenKai GB Screen
symbol_map U+2A700-U+2B73F LXGW WenKai GB Screen
symbol_map U+2B740-U+2B81F LXGW WenKai GB Screen
symbol_map U+2B820-U+2CEAF LXGW WenKai GB Screen
# 强制所有可能的 Emoji 区域都使用 Segoe UI Emoji
symbol_map U+231A-U+231B,U+23E9-U+23EC,U+23F0,U+23F3,U+25FD-U+25FE,U+2600-U+2693,U+2694-U+269C,U+269D,U+269E-U+269F,U+26A0-U+26A1,U+26A2-U+26B1,U+26B2-U+26BC,U+26BD-U+26BF,U+26C4-U+26C5,U+26C6-U+26C8,U+26C9-U+26CD,U+26CE-U+26CF,U+26D0-U+26D1,U+26D2-U+26D3,U+26D4-U+26D5,U+26D6-U+26D7,U+26D8-U+26D9,U+26DA-U+26DB,U+26DC-U+26DD,U+26DE-U+26DF,U+26E0-U+26E1,U+26E2,U+26E3-U+26E7,U+26E8-U+26E9,U+26EA-U+26EF,U+26F0-U+26F1,U+26F2-U+26F3,U+26F4-U+26F5,U+26F6-U+26F9,U+26FA-U+26FB,U+26FC-U+26FF,U+2700-U+27BF,U+1F000-U+1F9FF,U+1FA70-U+1FAFF Segoe UI Emoji

# 自动隐藏鼠标
mouse_hide_wait 3.0

# 鼠标右键粘贴
detect_urls no
copy_on_select clipboard
strip_trailing_spaces smart
select_by_word_characters ${}/&@_.
focus_follows_mouse yes
mouse_map right press grabbed,ungrabbed no-op
mouse_map right click grabbed,ungrabbed paste_from_clipboard
allow_hyperlinks no

# 关闭确认关闭窗口 
confirm_os_window_close 0

# 窗口颜色和透明度
foreground #f8f8f2
background #282a36
background_opacity 0.75

color0 #000000
color8 #44475a
#: black

color1 #ff5555
color9 #ff5555
#: red

color2  #50fa7b
color10 #50fa7b
#: green

color3  #f1fa8c
color11 #f1fa8c
#: yellow

color4  #bd93f9
color12 #bd93f9
#: blue

color5  #ff79c6
color13 #ff79c6
#: magenta

color6  #8be9fd
color14 #8be9fd
#: cyan

color7  #bbbbbb
color15 #ffffff
#: white

# neovide光标特效 
cursor_trail 3

# 自定义滚动快捷键
map ctrl+u scroll_page_up
map ctrl+e scroll_page_down

# 用Neovim打开kitty滚动缓冲
allow_remote_control yes
listen_on unix:/tmp/kitty
shell_integration enabled
# kitty-scrollback.nvim Kitten alias
action_alias kitty_scrollback_nvim kitten ~/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py
# Browse scrollback buffer in nvim
map kitty_mod+h kitty_scrollback_nvim
# Browse output of the last shell command in nvim
map kitty_mod+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output
# Show clicked command output in nvim
mouse_map ctrl+shift+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output
